import low_codimension_problems_algebraic_geometry_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace low_codimension_problems_algebraic_geometry_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end low_codimension_problems_algebraic_geometry_lemma_canonical_lane_mathlib
end HautevilleHouse
